name: test ci

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@master
    - name: Set up python
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"


    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: python -m pytest homework/

    - name: Run mypy
      run: mypy homework/

    - name: Run black
      run: black --check --diff homework/

    - name: Run isort
      run: isort --check-only --diff --profile black homework/

    - name: Run flake8
      run: flake8 homework/
